### PR TITLE
Updated to Opencore 0.6.2 and updated some kexts to lasted version

### PR DESCRIPTION
**Pull request by khoa-nv**

### CODE REVIEW

**Comment by toonvanstrijp** [comment]
@khoa-nv don't forget to disable `SecureBoot` [https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html](https://dortania.github.io/OpenCore-Post-Install/universal/security/applesecureboot.html)

**Comment by jaromeyer** [comment]
@khoa-nv i really appreciate your pr. however, im currently very busy and dont have the time to test this, so i wont merge it for now to keep the repo as stable as possible.

**Comment by Fyobl** [comment]
I haven’t tested this repo but I have managed to update to 0.6.2 along with all kext updated.

I’m happy to Chuck this on a stick and test it out for stability over the next few weeks?

**Comment by khoa-nv** [comment]
> I haven’t tested this repo but I have managed to update to 0.6.2 along with all kext updated.
> 
> I’m happy to Chuck this on a stick and test it out for stability over the next few weeks?

I'm using this EFI for my laptop now. It's working properly and hasn't any problems. Glad you created it.  I'm only making a small update for it.
image
image

**Comment by Fyobl** [comment]
@khoa-nv did you change anything in the config.plist file?

I know dummypowermanagerment was moved and some other stuff?

**Comment by khoa-nv** [comment]
> @khoa-nv did you change anything in the config.plist file?
> 
> I know dummypowermanagerment was moved and some other stuff?

Hackintool didn't display it but It still there. I add some kexts for my laptop but keep your origin.
image

**Comment by khoa-nv** [comment]
> @khoa-nv did you change anything in the config.plist file?
> 
> I know dummypowermanagerment was moved and some other stuff?

No, I didn't make any changes in config.plist.  I only replaced `BOOTX64.efi`, `OpenRuntime.efi`, `OpenCore.efi` files, and Kexts folder.

**Pull request closed without merging**
